/**
 * Private object storage for employee photographs.
 *
 * Objects are never served directly to browsers: route handlers authorise every
 * request and stream the bytes with `Cache-Control: private, no-store`. Keys are
 * generated by the server (`photos/<uuid>.jpg`, `photos/<uuid>-thumb.webp`) and
 * validated before any I/O, so user-supplied filenames never reach storage.
 */
export interface ObjectStorage {
  readonly driver: "local" | "supabase";
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  /** Returns null when the object does not exist. */
  get(key: string): Promise<Buffer | null>;
  /** Deletes objects; missing objects are ignored. */
  delete(keys: string[]): Promise<void>;
}

export class StorageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "StorageError";
  }
}

const KEY_RE = /^photos\/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(-thumb)?\.(jpg|webp)$/;

export function isValidStorageKey(key: string): boolean {
  return KEY_RE.test(key);
}

export function assertValidKey(key: string): void {
  if (!isValidStorageKey(key)) throw new StorageError("Invalid storage key");
}
